import { NextRequest } from 'next/server';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { errorResponse, ApiError } from '@/lib/api';
import { getWorkspace } from '@/lib/workspace';
import { getReportDataset } from '@/lib/reports';
import { formatLongDate } from '@/lib/format';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    const { organization } = await getWorkspace();
    const url = new URL(request.url);
    const from = url.searchParams.get('from') ? new Date(url.searchParams.get('from') as string) : undefined;
    const to = url.searchParams.get('to') ? new Date(url.searchParams.get('to') as string) : undefined;
    const report = await getReportDataset(organization.id, from, to);

    const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('Finora', 40, 50);
    doc.setFontSize(14);
    doc.text(`Organization: ${organization.name}`, 40, 74);
    doc.text(`Report period: ${from ? formatLongDate(from) : 'All time'} - ${to ? formatLongDate(to) : 'Present'}`, 40, 94);

    autoTable(doc, {
      startY: 120,
      head: [['Metric', 'Amount']],
      body: [
        ['Income', report.summary.income.toFixed(2)],
        ['Expense', report.summary.expenses.toFixed(2)],
        ['Net balance', report.summary.balance.toFixed(2)],
        ['Assets', report.balanceSheet.assets.toFixed(2)],
        ['Liabilities', report.balanceSheet.liabilities.toFixed(2)]
      ],
      styles: { fontSize: 10, cellPadding: 8 },
      headStyles: { fillColor: [212, 168, 83], textColor: 0 }
    });

    autoTable(doc, {
      startY: (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 200,
      head: [['Date', 'Asset', 'Type', 'Value', 'Details']],
      body: report.assets.length > 0
        ? report.assets.map((asset) => [
            formatLongDate(asset.purchaseDate ?? asset.createdAt),
            asset.name,
            asset.type,
            Number(asset.value).toFixed(2),
            asset.description ?? 'Recorded asset'
          ])
        : [['-', 'No assets recorded', '-', '-', '-']],
      styles: { fontSize: 8, cellPadding: 6 },
      headStyles: { fillColor: [22, 27, 34], textColor: 255 },
      margin: { top: 20 }
    });

    autoTable(doc, {
      startY: (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 200,
      head: [['Date', 'Liability', 'Type', 'Balance', 'Details']],
      body: report.liabilities.length > 0
        ? report.liabilities.map((liability) => [
            formatLongDate(liability.dueDate ?? liability.createdAt),
            liability.name,
            liability.type,
            Number(liability.balance).toFixed(2),
            liability.description ?? 'Recorded liability'
          ])
        : [['-', 'No liabilities recorded', '-', '-', '-']],
      styles: { fontSize: 8, cellPadding: 6 },
      headStyles: { fillColor: [22, 27, 34], textColor: 255 },
      margin: { top: 20 }
    });

    autoTable(doc, {
      startY: (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 200,
      head: [['Date', 'Description', 'Category', 'Debit', 'Credit', 'Balance']],
      body: report.ledger.map((entry) => [
        formatLongDate(entry.date),
        entry.description,
        entry.category?.name ?? 'Uncategorized',
        entry.type === 'EXPENSE' ? entry.amount.toFixed(2) : '-',
        entry.type === 'INCOME' ? entry.amount.toFixed(2) : '-',
        entry.runningBalance.toFixed(2)
      ]),
      styles: { fontSize: 8, cellPadding: 6 },
      headStyles: { fillColor: [22, 27, 34], textColor: 255 }
    });

    doc.setPage(doc.getNumberOfPages());
    doc.setFontSize(9);
    doc.text(`Generated by Finora`, 40, pageHeight - 30);
    doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth - 70, pageHeight - 30);

    const output = doc.output('arraybuffer');

    return new Response(output, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=finora-report.pdf`
      }
    });
  } catch (error) {
    return errorResponse(error instanceof Error ? error : new ApiError('PDF export failed.', 500));
  }
}